#!/usr/bin/env python3
"""FR-160 Phase B: turn a meson project's test registry into an emitrust
--test-entries file.

The emitter must never learn what a build system is -- it takes a list of
symbols.  This is the adapter that produces one from `meson introspect
--tests` (equivalently `<build>/meson-info/intro-tests.json`).  A CTest
adapter is the same shape over `ctest --show-only=json-v1`; keeping the
knowledge here and not in the driver is what makes FR-160 general.

Not `add_test_setup`: that only configures the default setup's exe_wrapper and
suite exclusions.  The wrapper does not appear in the introspected `cmd` --
meson applies it at run time -- so introspection hands back the bare
executable, which is what we want.

Every meson test declares `protocol: "exitcode"`, i.e. it passes iff the
binary exits 0.  That is exactly `#[test]` semantics (panic = fail), so the
oracle is inherited rather than invented.

Output: one `<c-source-path>\t<symbol>` line per entry point, `#` comments.
By default the symbol is `main` -- correct for a project whose test binary is
a plain `int main` running asserts.  For a project whose tests register
through a table (systemd's TEST() macro writes into a linker section, so main
is only a dispatcher), pass --entry-regex to name the bodies instead.
"""
import argparse, json, os, re, sys, collections

ap = argparse.ArgumentParser()
ap.add_argument("--build", required=True, help="meson build directory")
ap.add_argument("--crates", default="", help="emitted-crate root, to check symbols exist")
ap.add_argument("--root", default="", help="project source root (for crate naming)")
ap.add_argument("--entry-regex", default="",
                help="emit every function in the TU matching this instead of main "
                     r"(e.g. '^tu0_test_' for a table-registered suite)")
ap.add_argument("--multi-source", action="store_true",
                help="also emit tests whose binary is built from several .c files "
                     "(they need --link; one-TU tests do not)")
ap.add_argument("-o", "--out", default="-")
a = ap.parse_args()

info = os.path.join(a.build, "meson-info")
tests = json.load(open(os.path.join(info, "intro-tests.json")))
targets = json.load(open(os.path.join(info, "intro-targets.json")))

byfile = {}
for t in targets:
    for f in t.get("filename", []):
        byfile[os.path.normpath(f)] = t

stats = collections.Counter()
rows = []
for t in tests:
    stats["tests"] += 1
    if t["protocol"] != "exitcode":
        stats["skip: protocol != exitcode"] += 1
        continue
    tg = byfile.get(os.path.normpath(t["cmd"][0]))
    if tg is None:
        stats["skip: cmd[0] is not a built target"] += 1
        continue
    srcs = [os.path.normpath(f) for ts in tg.get("target_sources", [])
            for f in ts.get("sources", []) if f.endswith(".c")]
    if not srcs:
        stats["skip: target has no C sources"] += 1
        continue
    if len(srcs) > 1 and not a.multi_source:
        stats["skip: multi-source target (needs --link)"] += 1
        continue
    if len(t["cmd"]) > 1:
        stats["note: test passes argv (not modelled)"] += 1
    rows.append((t["name"], srcs))
    stats["selected"] += 1

def crate_dir(src):
    rel = os.path.relpath(src, a.root or os.path.dirname(a.build))
    return os.path.join(a.crates, rel.removesuffix(".c").replace("/", "_"))

out = []
rx = re.compile(a.entry_regex) if a.entry_regex else None
for name, srcs in rows:
    for src in srcs:
        syms = ["main"]
        if rx:
            lib = os.path.join(crate_dir(src), "src", "lib.rs")
            if not os.path.exists(lib):
                stats["drop: no emitted crate"] += 1
                continue
            syms = [m.group(1) for m in
                    re.finditer(r'^(?:pub )?fn ([A-Za-z0-9_]+)', open(lib).read(), re.M)
                    if rx.search(m.group(1))]
            if not syms:
                stats["drop: no symbol matched --entry-regex"] += 1
                continue
        for s in syms:
            out.append(f"{src}\t{s}\t# meson test '{name}'")
            stats["entries"] += 1

fh = sys.stdout if a.out == "-" else open(a.out, "w")
print("# generated by scripts/test-entries-meson.py -- do not edit", file=fh)
for line in out:
    print(line, file=fh)
for k, v in stats.most_common():
    print(f"{k:44s} {v}", file=sys.stderr)
